var natural = require('natural');
// // var tokenizer = new natural.WordTokenizer();

// // console.log(tokenizer.tokenize("The quick brown fox jumps over the lazy dog"));
// // // natural.PorterStemmer.attach();var natural = require('natural');

// natural.PorterStemmer.attach();
// var PorterStemmer = natural.PorterStemmer;
// let specClassifier = new natural.BayesClassifier(PorterStemmer,0.1);
// natural.PorterStemmer.attach();

// // // console.log("I can see that we are going to be friends".tokenizeAndStem());
// console.log("dog dogs Dog dogged".tokenizeAndStem());
// // console.log(natural.PorterStemmer.stem("quicking"));

// // // natural.PorterStemmerPt.attach();  // add methods to string

// // console.log("\n-- Use Porter Stemmer text in file sports.txt:");
// // // console.log("dog dogs Dog dogged".tokenizeAndStem());
// // console.log("I can see that we are going to be friends".tokenizeAndStem())
// // const data = "John Doe is hiiiiiii sometimes used to refer to a typical male in other contexts as well, in a similar manner to John Q.";
const data="ok i am  frustrated"
// const natural = require("natural");
const tokenizer = new natural.WordTokenizer();
const tokenizedData = tokenizer.tokenize(data);
// console.log(tokenizedData);
const stems = tokenizedData.map(natural.PorterStemmer.stem)
console.log(stems)
const words = ["typical", "types"]
console.log(natural.LevenshteinDistance.apply(null, words))
const corpus = ['hello','something'];
const spellcheck = new natural.Spellcheck(corpus);
const word = 'smthing';
console.log(spellcheck.isCorrect(word));
// console.log(spellcheck.getCorrections('helol', 1));

const Analyzer = natural.SentimentAnalyzer;
const stemmer = natural.PorterStemmer;
const analyzer = new Analyzer("English", stemmer, "afinn");
console.log(analyzer.getSentiment(stems));

// const spell = require('spell-checker-js')
 
// // Load dictionary
// spell.load('en')
 
// // Checking text
// const check = spell.check('Some text to check, blahblahblah, olololo')
 
// console.log(check)


// // var natural = require('natural');
// var metaphone = natural.Metaphone;
// var soundEx = natural.SoundEx;

// var wordA = `ho`;
// var wordB = 'yo';

// if (metaphone.compare(wordA, wordB))
//     console.log('They sound alike!');

// // We can also obtain the raw phonetics of a word using process()
// console.log(metaphone.process('phonetics'));



// // var Sentiment = require('sentiment');
// // var sentiment = new Sentiment();
// // var result = sentiment.analyze(s);
// // console.dir(result);  

// // const winkNLP = require( 'wink-nlp' );
// // // Load english language model.
// // const model = require( 'wink-eng-lite-web-model' );
// // // Instantiate winkNLP.
// // const nlp = winkNLP( model );
// // // Obtain "its" helper to extract item properties.
// // const its = nlp.its;
// // // Obtain "as" reducer helper to reduce a collection.
// // const as = nlp.as;
 
// // // NLP Code.
// // const text = 'Hello   World🌎! How are you?';
// // const doc = nlp.readDoc( text );
 
// // console.log( doc.out() );
// // // -> Hello   World🌎! How are you?
 
// // console.log( doc.sentences().out() );
// // // -> [ 'Hello   World🌎!', 'How are you?' ]
 
// // console.log( doc.entities().out( its.detail ) );
// // // -> [ { value: '🌎', type: 'EMOJI' } ]
 
// // console.log( doc.tokens().out() );
// // // -> [ 'Hello', 'World', '🌎', '!', 'How', 'are', 'you', '?' ]
 
// // // console.log( doc.tokens().out( its.type, as.freqTable ) );
// // var sentimentAnalysis = require('sentiment-analysis');
// //  var s="i do not love you"
// // console.log(sentimentAnalysis(s)); // +0.4


// const { sentence } = require('txtgen/dist/cjs/txtgen.js')
// const { addTemplates } = require('txtgen/dist/cjs/txtgen.js')
// // import {
// //   addTemplates
// // } from 'txtgen'

// const templates = [
//   '{{a_noun}} is {{a_noun}} from the right perspective',
//   'the {{noun}} of {{a_noun}} becomes {{an_adjective}} {{noun}}'
// ]

// addTemplates(templates)

// const { removeStopwords } = require('stopword')
// const oldString = 'ok i am really frustrated'.split(' ')
// const newString = removeStopwords(oldString)
// console.log(newString);

// var snowball = require('snowball');

// // Using String
// snowball.stemword('consignment'); // 'consign'

// // Using String and a specific language algorithm
// snowball.stemword('consignment', 'english'); // 'consign'


// const stemmernew = require("en-stemmer");
// console.log(stemmernew.stemmer("")); // according






// const spellchecker = require('spellchecker');

// let prompt = "How to corrct wrong spelling in a prompt?";

// // Split the prompt into words
// let words = prompt.split(" ");

// // Iterate through each word in the prompt
// for (let i = 0; i < words.length; i++) {
//   let word = words[i];

//   // Check if the word is misspelled
//   if (!spellchecker.isMisspelled(word)) {
//     continue;
//   }

//   // Get a list of suggested correct spellings
//   let suggestions = spellchecker.getSuggestionsForWord(word);

//   // Replace the misspelled word with the first suggested spelling
//   if (suggestions.length > 0) {
//     words[i] = suggestions[0];
//   }
// }

// // Join the corrected words back into a string prompt
// prompt = words.join(" ");
// console.log(prompt);

// const SymSpell = require('node-symspell')
// var dictionaryPath="../dictionaries";
// const maxEditDistance = 2
// const prefixLength = 7
// const symSpell = new SymSpell(maxEditDistance, prefixLength)
//  symSpell.loadDictionary(dictionaryPath, 0, 1)
//  symSpell.loadBigramDictionary(bigramPath, 0, 2)

// const typo = 'Can yu readthis messa ge despite thehorible sppelingmsitakes'
// const results = symSpell.lookupCompound(typo, maxEditDistance)

// console.log(results[0])
// // {
// // 	term: 'can you read this message despite the horrible spelling mistakes',
// // 	distance: 10,
// // 	count: 0
// // } 
// var SpellChecker = require('simple-spellchecker');
// SpellChecker.getDictionary("fr-FR", function(err, dictionary) {
//     if(!err) {
//         var misspelled = ! dictionary.spellCheck('maisonn');
//         if(misspelled) {
//             var suggestions = dictionary.getSuggestions('maisonn');
//         }
//     }
// });  

// // Initialization.
// var SpellChecker = require('simple-spellchecker');
// var myDictionary = null;

// // Load dictionary.
// SpellChecker.getDictionary("en-US", "./node_modules/simple-spellchecker/dict", function(err, result) {
//     if(!err) {
//         myDictionary = result;
//     }
// });

// // Define function for consult the dictionary.
// const ipcMain = require('ipc-main');
// ipcMain.on('checkspell', function(event, word) {
//     var res = null;
//     if(myDictionary != null && word != null) {
//         res = myDictionary.spellCheck(word);
//     }
//     event.returnValue = res;
// });

// const spellchecker = require('spellchecker');

// let prompt = "How to corrct wrong spelling in a prompt?";

// // Split the prompt into words
// let words = prompt.split(" ");

// // Iterate through each word in the prompt
// for (let i = 0; i < words.length; i++) {
//   let word = words[i];

//   // Check if the word is misspelled
//   if (!spellchecker.isMisspelled(word)) {
//     continue;
//   }

//   // Get a list of suggested correct spellings
//   let suggestions = spellchecker.getSuggestionsForWord(word);

//   // Replace the misspelled word with the first suggested spelling
//   if (suggestions.length > 0) {
//     words[i] = suggestions[0];
//   }
// }

// // Join the corrected words back into a string prompt
// prompt = words.join(" ");
// console.log(prompt);

const Typo = require('typo-js');

// Load English dictionary
// const dictionary = new Typo('en_US');

// // Function to correct a sentence
// function correctSentence(sentence) {
//     const words = sentence.split(' ');

//     // Correct each word
//     const correctedWords = words.map(word => {
//         // Check if the word is misspelled
//         if (!dictionary.check(word)) {
//             // Get suggestions for the misspelled word
//             const suggestions = dictionary.suggest(word);

//             // Choose the first suggestion as the correction
//             return suggestions.length > 0 ? suggestions[0] : word;
//         }

//         return word;
//     });

//     // Join the corrected words back into a sentence
//     return correctedWords.join(' ');
// }

// // Example usage
// const originalSentence = "whrer yuo go";
// const correctedSentence = correctSentence(originalSentence);

// // console.log(correctedSentence); // Output: "i love you"
// const Hunspell = require('hunspell-spellchecker');

// // Load English dictionary
// const dictionary = new Hunspell();

// // Function to correct a sentence
// function correctSentence(sentence) {
//     const words = sentence.split(' ');

//     // Correct each word
//     const correctedWords = words.map(word => {
//         // Check if the word is misspelled
//         if (!dictionary.spell(word)) {
//             // Get suggestions for the misspelled word
//             const suggestions = dictionary.suggest(word);

//             // Choose the first suggestion as the correction
//             return suggestions.length > 0 ? suggestions[0] : word;
//         }

//         return word;
//     });

//     // Join the corrected words back into a sentence
//     return correctedWords.join(' ');
// }

// // Example usage
// const originalSentence = "i loev yo";
// const correctedSentence = correctSentence(originalSentence);

// console.log(correctedSentence);
// var corpus = ['something', 'soothing'];
// var spellcheck = new natural.Spellcheck(corpus);

// console.log(spellcheck.getCorrections('myslf', 1)); 


// const words = ["typical", "types"]
// console.log(natural.LevenshteinDistance.apply(null, words))
// // const corpus = ['hello','something'];
// var corpus=["a",
// "able",
// "about",
// "absolute",
// "accept",
// "account",
// "achieve",
// "across",
// "act",
// "active",
// "actual",
// "add",
// "address",
// "admit",
// "advertise",
// "affect",
// "afford",
// "after",
// "afternoon",
// "again",
// "against",
// "age",
// "agent",
// "ago",
// "agree",
// "air",
// "all",
// "allow",
// "almost",
// "along",
// "already",
// "alright",
// "also",
// "although",
// "always",
// "america",
// "amount",
// "and",
// "another",
// "answer",
// "any",
// "apart",
// "apparent",
// "appear",
// "apply",
// "appoint",
// "approach",
// "appropriate",
// "area",
// "argue",
// "arm",
// "around",
// "arrange",
// "art",
// "as",
// "ask",
// "associate",
// "assume",
// "at",
// "attend",
// "authority",
// "available",
// "aware",
// "away",
// "awful",
// "baby",
// "back",
// "bad",
// "bag",
// "balance",
// "ball",
// "bank",
// "bar",
// "base",
// "basis",
// "be",
// "bear",
// "beat",
// "beauty",
// "because",
// "become",
// "bed",
// "before",
// "begin",
// "behind",
// "believe",
// "benefit",
// "best",
// "bet",
// "between",
// "big",
// "bill",
// "birth",
// "bit",
// "black",
// "bloke",
// "blood",
// "blow",
// "blue",
// "board",
// "boat",
// "body",
// "book",
// "both",
// "bother",
// "bottle",
// "bottom",
// "box",
// "boy",
// "break",
// "brief",
// "brilliant",
// "bring",
// "britain",
// "brother",
// "budget",
// "build",
// "bus",
// "business",
// "busy",
// "but",
// "buy",
// "by",
// "cake",
// "call",
// "can",
// "car",
// "card",
// "care",
// "carry",
// "case",
// "cat",
// "catch",
// "cause",
// "cent",
// "centre",
// "certain",
// "chair",
// "chairman",
// "chance",
// "change",
// "chap",
// "character",
// "charge",
// "cheap",
// "check",
// "child",
// "choice",
// "choose",
// "Christ",
// "Christmas",
// "church",
// "city",
// "claim",
// "class",
// "clean",
// "clear",
// "client",
// "clock",
// "close",
// "closes",
// "clothe",
// "club",
// "coffee",
// "cold",
// "colleague",
// "collect",
// "college",
// "colour",
// "come",
// "comment",
// "commit",
// "committee",
// "common",
// "community",
// "company",
// "compare",
// "complete",
// "compute",
// "concern",
// "condition",
// "confer",
// "consider",
// "consult",
// "contact",
// "continue",
// "contract",
// "control",
// "converse",
// "cook",
// "copy",
// "corner",
// "correct",
// "cost",
// "could",
// "council",
// "count",
// "country",
// "county",
// "couple",
// "course",
// "court",
// "cover",
// "create",
// "cross",
// "cup",
// "current",
// "cut",
// "dad",
// "danger",
// "date",
// "day",
// "dead",
// "deal",
// "dear",
// "debate",
// "decide",
// "decision",
// "deep",
// "definite",
// "degree",
// "department",
// "depend",
// "describe",
// "design",
// "detail",
// "develop",
// "die",
// "difference",
// "difficult",
// "dinner",
// "direct",
// "discuss",
// "district",
// "divide",
// "do",
// "doctor",
// "document",
// "dog",
// "door",
// "double",
// "doubt",
// "down",
// "draw",
// "dress",
// "drink",
// "drive",
// "drop",
// "dry",
// "due",
// "during",
// "each",
// "early",
// "east",
// "easy",
// "eat",
// "economy",
// "educate",
// "effect",
// "egg",
// "eight",
// "either",
// "elect",
// "electric",
// "eleven",
// "else",
// "employ",
// "encourage",
// "end",
// "engine",
// "english",
// "enjoy",
// "enough",
// "enter",
// "environment",
// "equal",
// "especial",
// "europe",
// "even",
// "evening",
// "ever",
// "every",
// "evidence",
// "exact",
// "example",
// "except",
// "excuse",
// "exercise",
// "exist",
// "expect",
// "expense",
// "experience",
// "explain",
// "express",
// "extra",
// "eye",
// "face",
// "fact",
// "fair",
// "fall",
// "family",
// "far",
// "farm",
// "fast",
// "father",
// "favour",
// "feed",
// "feel",
// "few",
// "field",
// "fight",
// "figure",
// "file",
// "fill",
// "film",
// "final",
// "finance",
// "find",
// "fine",
// "finish",
// "fire",
// "first",
// "fish",
// "fit",
// "five",
// "flat",
// "floor",
// "fly",
// "follow",
// "food",
// "foot",
// "for",
// "force",
// "forget",
// "form",
// "fortune",
// "forward",
// "four",
// "france",
// "free",
// "friday",
// "friend",
// "from",
// "front",
// "full",
// "fun",
// "function",
// "fund",
// "further",
// "future",
// "game",
// "garden",
// "gas",
// "general",
// "germany",
// "get",
// "girl",
// "give",
// "glass",
// "go",
// "god",
// "good",
// "goodbye",
// "govern",
// "grand",
// "grant",
// "great",
// "green",
// "ground",
// "group",
// "grow",
// "guess",
// "guy",
// "hair",
// "half",
// "hall",
// "hand",
// "hang",
// "happen",
// "happy",
// "hard",
// "hate",
// "have",
// "he",
// "head",
// "health",
// "hear",
// "heart",
// "heat",
// "heavy",
// "hell",
// "help",
// "here",
// "high",
// "history",
// "hit",
// "hold",
// "holiday",
// "home",
// "honest",
// "hope",
// "horse",
// "hospital",
// "hot",
// "hour",
// "house",
// "how",
// "however",
// "hullo",
// "hundred",
// "husband",
// "idea",
// "identify",
// "if",
// "imagine",
// "important",
// "improve",
// "in",
// "include",
// "income",
// "increase",
// "indeed",
// "individual",
// "industry",
// "inform",
// "inside",
// "instead",
// "insure",
// "interest",
// "into",
// "introduce",
// "invest",
// "involve",
// "issue",
// "it",
// "item",
// "jesus",
// "job",
// "join",
// "judge",
// "jump",
// "just",
// "keep",
// "key",
// "kid",
// "kill",
// "kind",
// "king",
// "kitchen",
// "knock",
// "know",
// "labour",
// "lad",
// "lady",
// "land",
// "language",
// "large",
// "last",
// "late",
// "laugh",
// "law",
// "lay",
// "lead",
// "learn",
// "leave",
// "left",
// "leg",
// "less",
// "let",
// "letter",
// "level",
// "lie",
// "life",
// "light",
// "like",
// "likely",
// "limit",
// "line",
// "link",
// "list",
// "listen",
// "little",
// "live",
// "load",
// "local",
// "lock",
// "london",
// "long",
// "look",
// "lord",
// "lose",
// "lot",
// "love",
// "low",
// "luck",
// "lunch",
// "machine",
// "main",
// "major",
// "make",
// "man",
// "manage",
// "many",
// "mark",
// "market",
// "marry",
// "match",
// "matter",
// "may",
// "maybe",
// "mean",
// "meaning",
// "measure",
// "meet",
// "member",
// "mention",
// "middle",
// "might",
// "mile",
// "milk",
// "million",
// "mind",
// "minister",
// "minus",
// "minute",
// "miss",
// "mister",
// "moment",
// "monday",
// "money",
// "month",
// "more",
// "morning",
// "most",
// "mother",
// "motion",
// "move",
// "mrs",
// "much",
// "music",
// "must",
// "name",
// "nation",
// "nature",
// "near",
// "necessary",
// "need",
// "never",
// "new",
// "news",
// "next",
// "nice",
// "night",
// "nine",
// "no",
// "non",
// "none",
// "normal",
// "north",
// "not",
// "note",
// "notice",
// "now",
// "number",
// "obvious",
// "occasion",
// "odd",
// "of",
// "off",
// "offer",
// "office",
// "often",
// "okay",
// "old",
// "on",
// "once",
// "one",
// "only",
// "open",
// "operate",
// "opportunity",
// "oppose",
// "or",
// "order",
// "organize",
// "original",
// "other",
// "otherwise",
// "ought",
// "out",
// "over",
// "own",
// "pack",
// "page",
// "paint",
// "pair",
// "paper",
// "paragraph",
// "pardon",
// "parent",
// "park",
// "part",
// "particular",
// "party",
// "pass",
// "past",
// "pay",
// "pence",
// "pension",
// "people",
// "per",
// "percent",
// "perfect",
// "perhaps",
// "period",
// "person",
// "photograph",
// "pick",
// "picture",
// "piece",
// "place",
// "plan",
// "play",
// "please",
// "plus",
// "point",
// "police",
// "policy",
// "politic",
// "poor",
// "position",
// "positive",
// "possible",
// "post",
// "pound",
// "power",
// "practise",
// "prepare",
// "present",
// "press",
// "pressure",
// "presume",
// "pretty",
// "previous",
// "price",
// "print",
// "private",
// "probable",
// "problem",
// "proceed",
// "process",
// "produce",
// "product",
// "programme",
// "project",
// "proper",
// "propose",
// "protect",
// "provide",
// "public",
// "pull",
// "purpose",
// "push",
// "put",
// "quality",
// "quarter",
// "question",
// "quick",
// "quid",
// "quiet",
// "quite",
// "radio",
// "rail",
// "raise",
// "range",
// "rate",
// "rather",
// "read",
// "ready",
// "real",
// "realise",
// "really",
// "reason",
// "receive",
// "recent",
// "reckon",
// "recognize",
// "recommend",
// "record",
// "red",
// "reduce",
// "refer",
// "regard",
// "region",
// "relation",
// "remember",
// "report",
// "represent",
// "require",
// "research",
// "resource",
// "respect",
// "responsible",
// "rest",
// "result",
// "return",
// "rid",
// "right",
// "ring",
// "rise",
// "road",
// "role",
// "roll",
// "room",
// "round",
// "rule",
// "run",
// "safe",
// "sale",
// "same",
// "saturday",
// "save",
// "say",
// "scheme",
// "school",
// "science",
// "score",
// "scotland",
// "seat",
// "second",
// "secretary",
// "section",
// "secure",
// "see",
// "seem",
// "self",
// "sell",
// "send",
// "sense",
// "separate",
// "serious",
// "serve",
// "service",
// "set",
// "settle",
// "seven",
// "sex",
// "shall",
// "share",
// "she",
// "sheet",
// "shoe",
// "shoot",
// "shop",
// "short",
// "should",
// "show",
// "shut",
// "sick",
// "side",
// "sign",
// "similar",
// "simple",
// "since",
// "sing",
// "single",
// "sir",
// "sister",
// "sit",
// "site",
// "situate",
// "six",
// "size",
// "sleep",
// "slight",
// "slow",
// "small",
// "smoke",
// "so",
// "social",
// "society",
// "some",
// "something",
// "son",
// "soon",
// "sorry",
// "sort",
// "sound",
// "south",
// "space",
// "speak",
// "special",
// "specific",
// "speed",
// "spell",
// "spend",
// "square",
// "staff",
// "stage",
// "stairs",
// "stand",
// "standard",
// "start",
// "state",
// "station",
// "stay",
// "step",
// "stick",
// "still",
// "stop",
// "story",
// "straight",
// "strategy",
// "street",
// "strike",
// "strong",
// "structure",
// "student",
// "study",
// "stuff",
// "stupid",
// "subject",
// "succeed",
// "such",
// "sudden",
// "suggest",
// "suit",
// "summer",
// "sun",
// "sunday",
// "supply",
// "support",
// "suppose",
// "sure",
// "surprise",
// "switch",
// "system",
// "table",
// "take",
// "talk",
// "tape",
// "tax",
// "tea",
// "teach",
// "team",
// "telephone",
// "television",
// "tell",
// "ten",
// "tend",
// "term",
// "terrible",
// "test",
// "than",
// "thank",
// "the",
// "then",
// "there",
// "therefore",
// "they",
// "thing",
// "think",
// "thirteen",
// "thirty",
// "this",
// "thou",
// "though",
// "thousand",
// "three",
// "through",
// "throw",
// "thursday",
// "tie",
// "time",
// "to",
// "today",
// "together",
// "tomorrow",
// "tonight",
// "too",
// "top",
// "total",
// "touch",
// "toward",
// "town",
// "trade",
// "traffic",
// "train",
// "transport",
// "travel",
// "treat",
// "tree",
// "trouble",
// "true",
// "trust",
// "try",
// "tuesday",
// "turn",
// "twelve",
// "twenty",
// "two",
// "type",
// "under",
// "understand",
// "union",
// "unit",
// "unite",
// "university",
// "unless",
// "until",
// "up",
// "upon",
// "use",
// "usual",
// "value",
// "various",
// "very",
// "video",
// "view",
// "village",
// "visit",
// "vote",
// "wage",
// "wait",
// "walk",
// "wall",
// "want",
// "war",
// "warm",
// "wash",
// "waste",
// "watch",
// "water",
// "way",
// "we",
// "wear",
// "wednesday",
// "wee",
// "week",
// "weigh",
// "welcome",
// "well",
// "west",
// "what",
// "when",
// "where",
// "whether",
// "which",
// "while",
// "white",
// "who",
// "whole",
// "why",
// "wide",
// "wife",
// "will",
// "win",
// "wind",
// "window",
// "wish",
// "with",
// "within",
// "without",
// "woman",
// "wonder",
// "wood",
// "word",
// "work",
// "world",
// "worry",
// "worse",
// "worth",
// "would",
// "write",
// "wrong",
// "year",
// "yes",
// "yesterday",
// "yet",
// "you",
// "young",
// "Armour",
//       "Barrymore",
//       "Cabot",
//       "Catholicism",
//       "Chihuahua",
//       "Christianity",
//       "Easter",
//       "Frenchman",
//       "Lowry",
//       "Mayer",
//       "Orientalism",
//       "Pharaoh",
//       "Pueblo",
//       "Pullman",
//       "Rodeo",
//       "Saturday",
//       "Sister",
//       "Snead",
//       "Syrah",
//       "Tuesday",
//       "Woodward",
//       "abbey",
//       "absence",
//       "absorption",
//       "abstinence",
//       "absurdity",
//       "abundance",
//       "acceptance",
//       "accessibility",
//       "accommodation",
//       "accomplice",
//       "accountability",
//       "accounting",
//       "accreditation",
//       "accuracy",
//       "acquiescence",
//       "acreage",
//       "actress",
//       "actuality",
//       "adage",
//       "adaptation",
//       "adherence",
//       "adjustment",
//       "adoption",
//       "adultery",
//       "advancement",
//       "advert",
//       "advertisement",
//       "advertising",
//       "advice",
//       "aesthetics",
//       "affinity",
//       "aggression",
//       "agriculture",
//       "aircraft",
//       "airtime",
//       "allegation",
//       "allegiance",
//       "allegory",
//       "allergy",
//       "allies",
//       "alligator",
//       "allocation",
//       "allotment",
//       "altercation",
//       "ambulance",
//       "ammonia",
//       "anatomy",
//       "anemia",
//       "ankle",
//       "announcement",
//       "annoyance",
//       "annuity",
//       "anomaly",
//       "anthropology",
//       "anxiety",
//       "apartheid",
//       "apologise",
//       "apostle",
//       "apparatus",
//       "appeasement",
//       "appellation",
//       "appendix",
//       "applause",
//       "appointment",
//       "appraisal",
//       "archery",
//       "archipelago",
//       "architecture",
//       "ardor",
//       "arrears",
//       "arrow",
//       "artisan",
//       "artistry",
//       "ascent",
//       "assembly",
//       "assignment",
//       "association",
//       "asthma",
//       "atheism",
//       "attacker",
//       "attraction",
//       "attractiveness",
//       "auspices",
//       "authority",
//       "avarice",
//       "aversion",
//       "aviation",
//       "babbling",
//       "backlash",
//       "baker",
//       "ballet",
//       "balls",
//       "banjo",
//       "baron",
//       "barrier",
//       "barrister",
//       "bases",
//       "basin",
//       "basis",
//       "battery",
//       "battling",
//       "bedtime",
//       "beginner",
//       "begun",
//       "bending",
//       "bicycle",
//       "billing",
//       "bingo",
//       "biography",
//       "biology",
//       "birthplace",
//       "blackberry",
//       "blather",
//       "blossom",
//       "boardroom",
//       "boasting",
//       "bodyguard",
//       "boldness",
//       "bomber",
//       "bondage",
//       "bonding",
//       "bones",
//       "bonus",
//       "bookmark",
//       "boomer",
//       "booty",
//       "bounds",
//       "bowling",
//       "brainstorming",
//       "breadth",
//       "breaker",
//       "brewer",
//       "brightness",
//       "broccoli",
//       "broth",
//       "brotherhood",
//       "browsing",
//       "brunch",
//       "brunt",
//       "building",
//       "bullion",
//       "bureaucracy",
//       "burglary",
//       "buyout",
//       "by-election",
//       "cabal",
//       "cabbage",
//       "calamity",
//       "campaign",
//       "canonization",
//       "captaincy",
//       "carcass",
//       "carrier",
//       "cartridge",
//       "cassette",
//       "catfish",
//       "caught",
//       "celebrity",
//       "cemetery",
//       "certainty",
//       "certification",
//       "charade",
//       "chasm",
//       "check-in",
//       "cheerleader",
//       "cheesecake",
//       "chemotherapy",
//       "chili",
//       "china",
//       "chivalry",
//       "cholera",
//       "cilantro",
//       "circus",
//       "civilisation",
//       "civility",
//       "clearance",
//       "clearing",
//       "clerk",
//       "climber",
//       "closeness",
//       "clothing",
//       "clutches",
//       "coaster",
//       "coconut",
//       "coding",
//       "collaborator",
//       "colleague",
//       "college",
//       "collision",
//       "colors",
//       "combustion",
//       "comedian",
//       "comer",
//       "commander",
//       "commemoration",
//       "commenter",
//       "commissioner",
//       "commune",
//       "competition",
//       "completeness",
//       "complexity",
//       "computing",
//       "comrade",
//       "concur",
//       "condominium",
//       "conduit",
//       "confidant",
//       "configuration",
//       "confiscation",
//       "conflagration",
//       "conflict",
//       "consist",
//       "consistency",
//       "consolidation",
//       "conspiracy",
//       "constable",
//       "consul",
//       "consultancy",
//       "contentment",
//       "contents",
//       "contractor",
//       "conversation",
//       "cornerstone",
//       "corpus",
//       "correlation",
//       "councilman",
//       "counselor",
//       "countdown",
//       "countryman",
//       "coverage",
//       "covering",
//       "coyote",
//       "cracker",
//       "creator",
//       "criminality",
//       "crocodile",
//       "cropping",
//       "cross-examination",
//       "crossover",
//       "crossroads",
//       "culprit",
//       "cumin",
//       "curator",
//       "curfew",
//       "cursor",
//       "custard",
//       "cutter",
//       "cyclist",
//       "cyclone",
//       "cylinder",
//       "cynicism",
//       "daddy",
//       "damsel",
//       "darkness",
//       "dawning",
//       "daybreak",
//       "dealing",
//       "dedication",
//       "deduction",
//       "defection",
//       "deference",
//       "deficiency",
//       "definition",
//       "deflation",
//       "degeneration",
//       "delegation",
//       "delicacy",
//       "delirium",
//       "deliverance",
//       "demeanor",
//       "demon",
//       "demonstration",
//       "denomination",
//       "dentist",
//       "departure",
//       "depletion",
//       "depression",
//       "designation",
//       "despotism",
//       "detention",
//       "developer",
//       "devolution",
//       "dexterity",
//       "diagnosis",
//       "dialect",
//       "differentiation",
//       "digger",
//       "digress",
//       "dioxide",
//       "diploma",
//       "disability",
//       "disarmament",
//       "discord",
//       "discovery",
//       "dishonesty",
//       "dismissal",
//       "disobedience",
//       "dispatcher",
//       "disservice",
//       "distribution",
//       "distributor",
//       "diver",
//       "diversity",
//       "docking",
//       "dollar",
//       "dominance",
//       "domination",
//       "dominion",
//       "donkey",
//       "doorstep",
//       "doorway",
//       "dossier",
//       "downside",
//       "drafting",
//       "drank",
//       "drilling",
//       "driver",
//       "drumming",
//       "drunkenness",
//       "duchess",
//       "ducking",
//       "dugout",
//       "dumps",
//       "dwelling",
//       "dynamics",
//       "eagerness",
//       "earnestness",
//       "earnings",
//       "eater",
//       "editor",
//       "effectiveness",
//       "electricity",
//       "elements",
//       "eloquence",
//       "emancipation",
//       "embodiment",
//       "embroidery",
//       "emperor",
//       "employment",
//       "encampment",
//       "enclosure",
//       "encouragement",
//       "endangerment",
//       "enlightenment",
//       "enthusiasm",
//       "environment",
//       "environs",
//       "envoy",
//       "epilepsy",
//       "equation",
//       "equator",
//       "error",
//       "espionage",
//       "estimation",
//       "evacuation",
//       "exaggeration",
//       "examination",
//       "exclamation",
//       "expediency",
//       "exploitation",
//       "extinction",
//       "eyewitness",
//       "falls",
//       "fascism",
//       "fastball",
//       "feces",
//       "feedback",
//       "ferocity",
//       "fertilization",
//       "fetish",
//       "finale",
//       "firing",
//       "fixing",
//       "flashing",
//       "flask",
//       "flora",
//       "fluke",
//       "folklore",
//       "follower",
//       "foothold",
//       "footing",
//       "forefinger",
//       "forefront",
//       "forgiveness",
//       "formality",
//       "formation",
//       "formula",
//       "foyer",
//       "fragmentation",
//       "framework",
//       "fraud",
//       "freestyle",
//       "frequency",
//       "friendliness",
//       "fries",
//       "frigate",
//       "fulfillment",
//       "function",
//       "functionality",
//       "fundraiser",
//       "fusion",
//       "futility",
//       "gallantry",
//       "gallery",
//       "genesis",
//       "genitals",
//       "girlfriend",
//       "glamour",
//       "glitter",
//       "glucose",
//       "google",
//       "grandeur",
//       "grappling",
//       "greens",
//       "gridlock",
//       "grocer",
//       "groundwork",
//       "grouping",
//       "gunman",
//       "gusto",
//       "habitation",
//       "hacker",
//       "hallway",
//       "hamburger",
//       "hammock",
//       "handling",
//       "hands",
//       "handshake",
//       "happiness",
//       "hardship",
//       "headcount",
//       "header",
//       "headquarters",
//       "heads",
//       "headset",
//       "hearth",
//       "hearts",
//       "heath",
//       "hegemony",
//       "height",
//       "hello",
//       "helper",
//       "helping",
//       "helplessness",
//       "hierarchy",
//       "hoarding",
//       "hockey",
//       "homeland",
//       "homer",
//       "honesty",
//       "horror",
//       "horseman",
//       "hostility",
//       "housing",
//       "humility",
//       "hurricane",
//       "iceberg",
//       "ignition",
//       "illness",
//       "illustration",
//       "illustrator",
//       "immunity",
//       "immunization",
//       "imperialism",
//       "imprisonment",
//       "inaccuracy",
//       "inaction",
//       "inactivity",
//       "inauguration",
//       "indecency",
//       "indicator",
//       "inevitability",
//       "infamy",
//       "infiltration",
//       "influx",
//       "iniquity",
//       "innocence",
//       "innovation",
//       "insanity",
//       "inspiration",
//       "instruction",
//       "instructor",
//       "insurer",
//       "interact",
//       "intercession",
//       "intercourse",
//       "intermission",
//       "interpretation",
//       "intersection",
//       "interval",
//       "intolerance",
//       "intruder",
//       "invasion",
//       "investment",
//       "involvement",
//       "irrigation",
//       "iteration",
//       "jenny",
//       "jogging",
//       "jones",
//       "joseph",
//       "juggernaut",
//       "juncture",
//       "jurisprudence",
//       "juror",
//       "kangaroo",
//       "kingdom",
//       "knocking",
//       "laborer",
//       "larceny",
//       "laurels",
//       "layout",
//       "leadership",
//       "leasing",
//       "legislation",
//       "leopard",
//       "liberation",
//       "licence",
//       "lifeblood",
//       "lifeline",
//       "ligament",
//       "lighting",
//       "likeness",
//       "line-up",
//       "lineage",
//       "liner",
//       "lineup",
//       "liquidation",
//       "listener",
//       "literature",
//       "litigation",
//       "litre",
//       "loathing",
//       "locality",
//       "lodging",
//       "logic",
//       "longevity",
//       "lookout",
//       "lordship",
//       "lustre",
//       "ma'am",
//       "machinery",
//       "madness",
//       "magnificence",
//       "mahogany",
//       "mailing",
//       "mainframe",
//       "maintenance",
//       "majority",
//       "manga",
//       "mango",
//       "manifesto",
//       "mantra",
//       "manufacturer",
//       "maple",
//       "martin",
//       "martyrdom",
//       "mathematician",
//       "matrix",
//       "matron",
//       "mayhem",
//       "mayor",
//       "means",
//       "meantime",
//       "measurement",
//       "mechanics",
//       "mediator",
//       "medics",
//       "melodrama",
//       "memory",
//       "mentality",
//       "metaphysics",
//       "method",
//       "metre",
//       "miner",
//       "mirth",
//       "misconception",
//       "misery",
//       "mishap",
//       "misunderstanding",
//       "mobility",
//       "molasses",
//       "momentum",
//       "monarchy",
//       "monument",
//       "morale",
//       "mortality",
//       "motto",
//       "mouthful",
//       "mouthpiece",
//       "mover",
//       "movie",
//       "mowing",
//       "murderer",
//       "musician",
//       "mutation",
//       "mythology",
//       "narration",
//       "narrator",
//       "nationality",
//       "negligence",
//       "neighborhood",
//       "neighbour",
//       "nervousness",
//       "networking",
//       "nexus",
//       "nightmare",
//       "nobility",
//       "nobody",
//       "noodle",
//       "normalcy",
//       "notification",
//       "nourishment",
//       "novella",
//       "nucleus",
//       "nuisance",
//       "nursery",
//       "nutrition",
//       "nylon",
//       "oasis",
//       "obscenity",
//       "obscurity",
//       "observer",
//       "offense",
//       "onslaught",
//       "operation",
//       "opportunity",
//       "opposition",
//       "oracle",
//       "orchestra",
//       "organisation",
//       "organizer",
//       "orientation",
//       "originality",
//       "ounce",
//       "outage",
//       "outcome",
//       "outdoors",
//       "outfield",
//       "outing",
//       "outpost",
//       "outset",
//       "overseer",
//       "owner",
//       "oxygen",
//       "pairing",
//       "panther",
//       "paradox",
//       "parliament",
//       "parsley",
//       "parson",
//       "passenger",
//       "pasta",
//       "patchwork",
//       "pathos",
//       "patriotism",
//       "pendulum",
//       "penguin",
//       "permission",
//       "persona",
//       "perusal",
//       "pessimism",
//       "peter",
//       "philosopher",
//       "phosphorus",
//       "phrasing",
//       "physique",
//       "piles",
//       "plateau",
//       "playing",
//       "plaza",
//       "plethora",
//       "plurality",
//       "pneumonia",
//       "pointer",
//       "poker",
//       "policeman",
//       "polling",
//       "poster",
//       "posterity",
//       "posting",
//       "postponement",
//       "potassium",
//       "pottery",
//       "poultry",
//       "pounding",
//       "pragmatism",
//       "precedence",
//       "precinct",
//       "preoccupation",
//       "pretense",
//       "priesthood",
//       "prisoner",
//       "privacy",
//       "probation",
//       "proceeding",
//       "proceedings",
//       "processing",
//       "processor",
//       "progression",
//       "projection",
//       "prominence",
//       "propensity",
//       "prophecy",
//       "prorogation",
//       "prospectus",
//       "protein",
//       "prototype",
//       "providence",
//       "provider",
//       "provocation",
//       "proximity",
//       "puberty",
//       "publicist",
//       "publicity",
//       "publisher",
//       "pundit",
//       "putting",
//       "quantity",
//       "quart",
//       "quilting",
//       "quorum",
//       "racism",
//       "radiance",
//       "ralph",
//       "rancher",
//       "ranger",
//       "rapidity",
//       "rapport",
//       "ratification",
//       "rationality",
//       "reaction",
//       "reader",
//       "reassurance",
//       "rebirth",
//       "receptor",
//       "recipe",
//       "recognition",
//       "recourse",
//       "recreation",
//       "rector",
//       "recurrence",
//       "redemption",
//       "redistribution",
//       "redundancy",
//       "refinery",
//       "reformer",
//       "refrigerator",
//       "regularity",
//       "regulator",
//       "reinforcement",
//       "reins",
//       "reinstatement",
//       "relativism",
//       "relaxation",
//       "rendition",
//       "repayment",
//       "repentance",
//       "repertoire",
//       "repository",
//       "republic",
//       "reputation",
//       "resentment",
//       "residency",
//       "resignation",
//       "restaurant",
//       "resurgence",
//       "retailer",
//       "retention",
//       "retirement",
//       "reviewer",
//       "riches",
//       "righteousness",
//       "roadblock",
//       "robber",
//       "rocks",
//       "rubbing",
//       "runoff",
//       "saloon",
//       "salvation",
//       "sarcasm",
//       "saucer",
//       "savior",
//       "scarcity",
//       "scenario",
//       "scenery",
//       "schism",
//       "scholarship",
//       "schoolboy",
//       "schooner",
//       "scissors",
//       "scolding",
//       "scooter",
//       "scouring",
//       "scrimmage",
//       "scrum",
//       "seating",
//       "sediment",
//       "seduction",
//       "seeder",
//       "seizure",
//       "self-confidence",
//       "self-control",
//       "self-respect",
//       "semicolon",
//       "semiconductor",
//       "semifinal",
//       "senator",
//       "sending",
//       "serenity",
//       "seriousness",
//       "servitude",
//       "sesame",
//       "setup",
//       "sewing",
//       "sharpness",
//       "shaving",
//       "shoplifting",
//       "shopping",
//       "siding",
//       "simplicity",
//       "simulation",
//       "sinking",
//       "skate",
//       "sloth",
//       "slugger",
//       "snack",
//       "snail",
//       "snapshot",
//       "snark",
//       "soccer",
//       "solemnity",
//       "solicitation",
//       "solitude",
//       "somewhere",
//       "sophistication",
//       "sorcery",
//       "souvenir",
//       "spaghetti",
//       "specification",
//       "specimen",
//       "specs",
//       "spectacle",
//       "spectre",
//       "speculation",
//       "sperm",
//       "spoiler",
//       "squad",
//       "squid",
//       "staging",
//       "stagnation",
//       "staircase",
//       "stairway",
//       "stamina",
//       "standpoint",
//       "standstill",
//       "stanza",
//       "statement",
//       "stillness",
//       "stimulus",
//       "stocks",
//       "stole",
//       "stoppage",
//       "storey",
//       "storyteller",
//       "stylus",
//       "subcommittee",
//       "subscription",
//       "subsidy",
//       "suburb",
//       "success",
//       "sufferer",
//       "supposition",
//       "suspension",
//       "sweater",
//       "sweepstakes",
//       "swimmer",
//       "syndrome",
//       "synopsis",
//       "syntax",
//       "system",
//       "tablespoon",
//       "taker",
//       "tavern",
//       "technology",
//       "telephony",
//       "template",
//       "tempo",
//       "tendency",
//       "tendon",
//       "terrier",
//       "terror",
//       "terry",
//       "theater",
//       "theology",
//       "therapy",
//       "thicket",
//       "thoroughfare",
//       "threshold",
//       "thriller",
//       "thunderstorm",
//       "ticker",
//       "tiger",
//       "tights",
//       "to-day",
//       "tossing",
//       "touchdown",
//       "tourist",
//       "tourney",
//       "toxicity",
//       "tracing",
//       "tractor",
//       "translation",
//       "transmission",
//       "transmitter",
//       "trauma",
//       "traveler",
//       "treadmill",
//       "trilogy",
//       "trout",
//       "tuning",
//       "twenties",
//       "tycoon",
//       "tyrant",
//       "ultimatum",
//       "underdog",
//       "underwear",
//       "unhappiness",
//       "unification",
//       "university",
//       "uprising",
//       "vaccination",
//       "validity",
//       "vampire",
//       "vanguard",
//       "variation",
//       "vegetation",
//       "verification",
//       "viability",
//       "vicinity",
//       "victory",
//       "viewpoint",
//       "villa",
//       "vindication",
//       "violation",
//       "vista",
//       "vocalist",
//       "vogue",
//       "volcano",
//       "voltage",
//       "vomiting",
//       "vulnerability",
//       "waistcoat",
//       "waitress",
//       "wardrobe",
//       "warmth",
//       "watchdog",
//       "wealth",
//       "weariness",
//       "whereabouts",
//       "whisky",
//       "whiteness",
//       "widget",
//       "width",
//       "windfall",
//       "wiring",
//       "witchcraft",
//       "withholding",
//       "womanhood",
//       "words",
//       "workman",
//       "youngster",
//       "abnormally",
//       "absentmindedly",
//       "accidentally",
//       "acidly",
//       "actually",
//       "adventurously",
//       "afterwards",
//       "almost",
//       "always",
//       "angrily",
//       "annually",
//       "anxiously",
//       "arrogantly",
//       "awkwardly",
//       "badly",
//       "bashfully",
//       "beautifully",
//       "bitterly",
//       "bleakly",
//       "blindly",
//       "blissfully",
//       "boastfully",
//       "boldly",
//       "bravely",
//       "briefly",
//       "brightly",
//       "briskly",
//       "broadly",
//       "busily",
//       "calmly",
//       "carefully",
//       "carelessly",
//       "cautiously",
//       "certainly",
//       "cheerfully",
//       "clearly",
//       "cleverly",
//       "closely",
//       "coaxingly",
//       "colorfully",
//       "commonly",
//       "continually",
//       "coolly",
//       "correctly",
//       "courageously",
//       "crossly",
//       "cruelly",
//       "curiously",
//       "daily",
//       "daintily",
//       "dearly",
//       "deceivingly",
//       "deeply",
//       "defiantly",
//       "deliberately",
//       "delightfully",
//       "diligently",
//       "dimly",
//       "doubtfully",
//       "dreamily",
//       "easily",
//       "elegantly",
//       "energetically",
//       "enormously",
//       "enthusiastically",
//       "equally",
//       "especially",
//       "even",
//       "evenly",
//       "eventually",
//       "exactly",
//       "excitedly",
//       "extremely",
//       "fairly",
//       "faithfully",
//       "famously",
//       "far",
//       "fast",
//       "fatally",
//       "ferociously",
//       "fervently",
//       "fiercely",
//       "fondly",
//       "foolishly",
//       "fortunately",
//       "frankly",
//       "frantically",
//       "freely",
//       "frenetically",
//       "frightfully",
//       "fully",
//       "furiously",
//       "generally",
//       "generously",
//       "gently",
//       "gladly",
//       "gleefully",
//       "gracefully",
//       "gratefully",
//       "greatly",
//       "greedily",
//       "happily",
//       "hastily",
//       "healthily",
//       "heavily",
//       "helpfully",
//       "helplessly",
//       "highly",
//       "honestly",
//       "hopelessly",
//       "hourly",
//       "hungrily",
//       "immediately",
//       "innocently",
//       "inquisitively",
//       "instantly",
//       "intensely",
//       "intently",
//       "interestingly",
//       "inwardly",
//       "irritably",
//       "jaggedly",
//       "jealously",
//       "joshingly",
//       "jovially",
//       "joyfully",
//       "joyously",
//       "jubilantly",
//       "judgementally",
//       "justly",
//       "keenly",
//       "kiddingly",
//       "kindheartedly",
//       "kindly",
//       "kissingly",
//       "knavishly",
//       "knottily",
//       "knowingly",
//       "knowledgeably",
//       "kookily",
//       "lazily",
//       "less",
//       "lightly",
//       "likely",
//       "limply",
//       "lively",
//       "loftily",
//       "longingly",
//       "loosely",
//       "loudly",
//       "lovingly",
//       "loyally",
//       "madly",
//       "majestically",
//       "meaningfully",
//       "mechanically",
//       "merrily",
//       "miserably",
//       "mockingly",
//       "monthly",
//       "more",
//       "mortally",
//       "mostly",
//       "mysteriously",
//       "naturally",
//       "nearly",
//       "neatly",
//       "needily",
//       "nervously",
//       "never",
//       "nicely",
//       "noisily",
//       "not",
//       "obediently",
//       "obnoxiously",
//       "oddly",
//       "offensively",
//       "officially",
//       "often",
//       "only",
//       "openly",
//       "optimistically",
//       "overconfidently",
//       "owlishly",
//       "painfully",
//       "partially",
//       "patiently",
//       "perfectly",
//       "physically",
//       "playfully",
//       "politely",
//       "poorly",
//       "positively",
//       "potentially",
//       "powerfully",
//       "promptly",
//       "properly",
//       "punctually",
//       "quaintly",
//       "quarrelsomely",
//       "queasily",
//       "queerly",
//       "questionably",
//       "questioningly",
//       "quicker",
//       "quickly",
//       "quietly",
//       "quirkily",
//       "quizzically",
//       "rapidly",
//       "rarely",
//       "readily",
//       "really",
//       "reassuringly",
//       "recklessly",
//       "regularly",
//       "reluctantly",
//       "repeatedly",
//       "reproachfully",
//       "restfully",
//       "righteously",
//       "rightfully",
//       "rigidly",
//       "roughly",
//       "rudely",
//       "sadly",
//       "safely",
//       "scarcely",
//       "scarily",
//       "searchingly",
//       "sedately",
//       "seemingly",
//       "seldom",
//       "selfishly",
//       "separately",
//       "seriously",
//       "shakily",
//       "sharply",
//       "sheepishly",
//       "shrilly",
//       "shyly",
//       "silently",
//       "sleepily",
//       "slowly",
//       "smoothly",
//       "softly",
//       "solemnly",
//       "solidly",
//       "sometimes",
//       "soon",
//       "speedily",
//       "stealthily",
//       "sternly",
//       "strictly",
//       "successfully",
//       "suddenly",
//       "surprisingly",
//       "suspiciously",
//       "sweetly",
//       "swiftly",
//       "sympathetically",
//       "tenderly",
//       "tensely",
//       "terribly",
//       "thankfully",
//       "thoroughly",
//       "thoughtfully",
//       "tightly",
//       "tomorrow",
//       "too",
//       "tremendously",
//       "triumphantly",
//       "truly",
//       "truthfully",
//       "ultimately",
//       "unabashedly",
//       "unaccountably",
//       "unbearably",
//       "unethically",
//       "unexpectedly",
//       "unfortunately",
//       "unimpressively",
//       "unnaturally",
//       "unnecessarily",
//       "upbeat",
//       "upliftingly",
//       "upright",
//       "upside-down",
//       "upward",
//       "upwardly",
//       "urgently",
//       "usefully",
//       "uselessly",
//       "usually",
//       "utterly",
//       "vacantly",
//       "vaguely",
//       "vainly",
//       "valiantly",
//       "vastly",
//       "verbally",
//       "very",
//       "viciously",
//       "victoriously",
//       "violently",
//       "vivaciously",
//       "voluntarily",
//       "warmly",
//       "weakly",
//       "wearily",
//       "well",
//       "wetly",
//       "wholly",
//       "wildly",
//       "willfully",
//       "wisely",
//       "woefully",
//       "wonderfully",
//       "worriedly",
//       "wrongly",
//       "yawningly",
//       "yearly",
//       "yearningly",
//       "yesterday",
//       "yieldingly",
//       "youthfully"
// ];
// const spellcheck = new natural.Spellcheck(corpus);
// const word = 'lover';
// function findMostRelevantWord(searchWord, wordArray) {
//   // Calculate the Levenshtein distance between two strings
//   function levenshteinDistance(a, b) {
//       if (a.length === 0) return b.length;
//       if (b.length === 0) return a.length;

//       const matrix = [];

//       // Initialize the matrix
//       for (let i = 0; i <= b.length; i++) {
//           matrix[i] = [i];
//       }

//       for (let j = 0; j <= a.length; j++) {
//           matrix[0][j] = j;
//       }

//       // Fill in the matrix
//       for (let i = 1; i <= b.length; i++) {
//           for (let j = 1; j <= a.length; j++) {
//               const cost = a[j - 1] === b[i - 1] ? 0 : 1;
//               matrix[i][j] = Math.min(
//                   matrix[i - 1][j] + 1, // Deletion
//                   matrix[i][j - 1] + 1, // Insertion
//                   matrix[i - 1][j - 1] + cost // Substitution
//               );
//           }
//       }

//       return matrix[b.length][a.length];
//   }

//   // Find the word with the smallest Levenshtein distance
//   let minDistance = Infinity;
//   let mostRelevantWord = null;

//   for (const word of wordArray) {
//       const distance = levenshteinDistance(searchWord, word);
//       if (distance < minDistance) {
//           minDistance = distance;
//           mostRelevantWord = word;
//       }
//   }

//   return mostRelevantWord;
// }

// // // Example usage
// // const searchWord = "hola";
// // const wordArray = ["aple", "appl", "orange", "banana", "appple"];


// console.log(spellcheck.isCorrect(word));
// console.log(spellcheck.getCorrections(word, 1));
// wordarray=spellcheck.getCorrections(word, 1);
// const mostRelevantWord = findMostRelevantWord(word, wordarray);
// console.log(mostRelevantWord); // Output: "appl"

// console.log(natural.HammingDistance("bye", "byeb", false));

